name: Run Trading Bot
on:
    schedule:
        - cron: '*/5 * * * *' # Runs every 5 minutes
jobs:
    run-bot:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - run: npm install
            - run: npm start
